### ISSUE TITLE
Cannot Install viewephys gui

### ISSUE THREAD

**Issue by EmmaCondon** [int-brain-lab/neuropixels_course_2024#3]
Hi, I am following the installation instructions to prepare for the course next week. However, I am receiving an error at the following stage:
"Checking the viewephys gui
To check the installation of the viewephys gui (used in assignment 1.8.3) has worked correctly, open a terminal and type the following

conda activate iblenv
viewephys"

When I entered this into the terminal (using Ubuntu on a Linux system) I received an error that neurodsp was not installed.
I did "pip install neurodsp" and it successfully installed. I tried again to viewephys and I am now getting the following error:
"(iblenv) lejla@ibp10346:~$ viewephys
Traceback (most recent call last):
  File "/home/lejla/anaconda3/envs/iblenv/bin/viewephys", line 5, in <module>
    from viewephys.command_line import viewephys
  File "/home/lejla/anaconda3/envs/iblenv/lib/python3.11/site-packages/viewephys/command_line.py", line 8, in <module>
    from viewephys.gui import EphysBinViewer
  File "/home/lejla/anaconda3/envs/iblenv/lib/python3.11/site-packages/viewephys/gui.py", line 11, in <module>
    from neurodsp import voltage
ImportError: cannot import name 'voltage' from 'neurodsp' (/home/lejla/anaconda3/envs/iblenv/lib/python3.11/site-packages/neurodsp/__init__.py)"

I am not very familiar with using a terminal or python so any advice would be greatly appreciated!

Many thanks :)

**Comment by mayofaulkner** [comment]
Hello,

Please could you do the following
```
conda activate iblenv
pip uninstall neurodsp
pip uninstall viewephys
```
Hit yes when prompted.

Then could you run
```
pip install git+https://github.com/int-brain-lab/viewephys.git
```

If you run `viewephys` the gui should then display! 

Let me know if not!

Apologies for this, I have fixed the instructions to ensure this won't happen for others!

**Comment by EmmaCondon** [comment]
Hi @mayofaulkner, thank you for the speedy reply. I followed your instructions and it worked perfectly :+1:
