### ISSUE TITLE
Unable to install viewephys gui

### ISSUE THREAD

**Issue by Anjana1072** [int-brain-lab/neuropixels_course_2024#5]
Hi!!! I have installed Viewephys and have gotten the ephys bin viewer but I am not able to install alignment gui following that in windows. Would be glad if I get some help regarding this.
![Screenshot_neuropixel](https://github.com/user-attachments/assets/e1b1d6bf-60a0-4a0b-b139-73e95238ff72)

**Comment by mayofaulkner** [comment]
Hi, do you close the ephys viewer before attempting to launch the alignment gui?

**Comment by Anjana1072** [comment]
No, ephys viewer is open only. I cannot launch ephys-align and when I tried asking ChatGPT it said there is some error with the path. I reinstalled viewephys again and it appeared in scripts directory but am still not able to launch the alignment GUI

**Comment by mayofaulkner** [comment]
So just to make sure you will need to close the viewephys window and then launch the command ephys-align. Is this what you are currently doing?

**Comment by Anjana1072** [comment]
I launched it without closing the viewephys window. Got it now. Thanks a lot
